apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: d2olqouhv-go-gitops
  description: This is GitOps manifest for d2olqouhv-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: d2olqouhv-go
    backstage.io/kubernetes-id: d2olqouhv-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:d2olqouhv-go
