apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d2olqouhv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d2olqouhv-go 
  name: d2olqouhv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: d2olqouhv-go 
